#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Decision record domain and application port.
//!
//! This crate stores audit-ready decision snapshots. It deliberately keeps
//! external provider details as JSON snapshots so Qwen, quant, and broker
//! adapters can evolve without losing the exact input and output seen at
//! decision time.

use std::sync::Arc;

use async_trait::async_trait;
use rust_decimal::Decimal;
use serde::Serialize;
use serde_json::Value;
use strategy_policy::PolicyRef;
use time::OffsetDateTime;
use uuid::Uuid;

const MAX_SYMBOL_LEN: usize = 32;
const MAX_SUMMARY_LEN: usize = 2000;
const DEFAULT_RECORD_LIST_LIMIT: u16 = 50;
const MAX_RECORD_LIST_LIMIT: u16 = 200;
const MAX_MANUAL_EXECUTION_NOTE_LEN: usize = 500;

/// Execution status captured by a decision record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionExecutionStatus {
    /// The plan is active and the preview date matches the schedule.
    Due,
    /// The plan is active but the preview date is not the schedule date.
    Waiting,
    /// The plan is inactive and should not execute.
    Inactive,
}

/// 生成一条决策记录的策略版本与通用推荐快照。
///
/// 该结构仅保存策略身份和已确定的推荐输出；70/20/10 或其他策略专属证据仍保留在
/// 各自的输入快照列中。旧记录可为 `None`，以保持迁移前审计历史可读。
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct DecisionPolicyEvidence {
    /// 生成推荐的不可变策略版本。
    pub policy: PolicyRef,
    /// 不包含凭据的通用推荐快照。
    pub recommendation_snapshot: Value,
}

/// Persisted decision record for one preview or execution.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct DecisionRecord {
    /// Record ID.
    pub id: Uuid,
    /// Related investment plan ID.
    pub plan_id: Uuid,
    /// Investment symbol snapshot.
    pub symbol: String,
    /// Currency snapshot.
    pub currency: String,
    /// Execution status snapshot.
    pub execution_status: DecisionExecutionStatus,
    /// Optional planned contribution encoded as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub planned_contribution: Option<String>,
    /// Execution preview snapshot, including schedule and bucket split.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub execution_snapshot: Value,
    /// Fundamental input snapshot used by the decision engine.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub fundamental_snapshot: Value,
    /// Trend input snapshot used by the decision engine.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub trend_snapshot: Value,
    /// Optional AI sentiment snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sentiment_snapshot: Option<Value>,
    /// Decision output snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub decision_snapshot: Value,
    /// 可选的结构化策略版本与推荐快照；迁移前记录保持为空。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy_evidence: Option<DecisionPolicyEvidence>,
    /// Optional broker order request snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_request: Option<Value>,
    /// Optional broker order acknowledgement snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_ack: Option<Value>,
    /// User-facing summary generated for this decision.
    pub summary: String,
    /// Creation time.
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
}

/// Input used to create a decision record.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct CreateDecisionRecord {
    /// Related investment plan ID.
    pub plan_id: Uuid,
    /// Investment symbol snapshot.
    pub symbol: String,
    /// Currency snapshot.
    pub currency: String,
    /// Execution status snapshot.
    pub execution_status: DecisionExecutionStatus,
    /// Optional planned contribution encoded as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub planned_contribution: Option<String>,
    /// Execution preview snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub execution_snapshot: Value,
    /// Fundamental input snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub fundamental_snapshot: Value,
    /// Trend input snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub trend_snapshot: Value,
    /// Optional AI sentiment snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sentiment_snapshot: Option<Value>,
    /// Decision output snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub decision_snapshot: Value,
    /// 本次决策使用的结构化策略版本与推荐快照。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy_evidence: Option<DecisionPolicyEvidence>,
    /// Optional broker order request snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_request: Option<Value>,
    /// Optional broker order acknowledgement snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_ack: Option<Value>,
    /// User-facing summary generated for this decision.
    pub summary: String,
}

/// Broker result used to complete a previously persisted order intention.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct CompleteDecisionRecord {
    /// Broker acknowledgement snapshot for the already-submitted order.
    ///
    /// The snapshot must not contain account credentials or other secrets.
    pub broker_order_ack: Value,
    /// Final user-facing summary after the broker acknowledgement.
    pub summary: String,
}

/// Broker order intent atomically attached to an existing approval record before submission.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct AttachBrokerOrderRequest {
    /// Validated paper-order request snapshot without credentials.
    pub broker_order_request: Value,
    /// User-facing state explaining that the broker outcome is pending.
    pub summary: String,
}

/// User-reported outcome appended to an immutable decision record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ManualExecutionOutcome {
    /// The user reports completing the intended investment action.
    Executed,
    /// The user reports intentionally taking no action.
    Skipped,
    /// The user reports completing only part of the intended action.
    Partial,
}

/// Provenance attached to a manual execution event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ManualExecutionSource {
    /// The event is an unverified statement entered by the user.
    UserReported,
}

/// One append-only user-reported execution event linked to a decision record.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ManualExecutionEvent {
    /// Client-generated event ID used to make retries explicit and duplicate-safe.
    pub id: Uuid,
    /// Immutable decision record to which the user response applies.
    pub decision_record_id: Uuid,
    /// Plan snapshot inherited from the referenced decision record.
    pub plan_id: Uuid,
    /// User-reported execution outcome.
    pub outcome: ManualExecutionOutcome,
    /// Actual amount reported by the user; absent only when the outcome is skipped.
    #[serde(
        with = "rust_decimal::serde::str_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub actual_amount: Option<Decimal>,
    /// Currency snapshot inherited from the referenced decision record.
    pub currency: String,
    /// Optional bounded user note.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// When the user says the execution outcome occurred.
    #[serde(with = "time::serde::rfc3339")]
    pub occurred_at: OffsetDateTime,
    /// When IndexLink appended this event to the local journal.
    #[serde(with = "time::serde::rfc3339")]
    pub recorded_at: OffsetDateTime,
    /// Explicitly marks the event as user-reported rather than broker-verified.
    pub source: ManualExecutionSource,
}

/// Input for appending one manual execution event.
#[derive(Debug, Clone, PartialEq)]
pub struct CreateManualExecutionEvent {
    /// Client-generated event ID; retries must reuse the same value.
    pub id: Uuid,
    /// Immutable decision record to which this event applies.
    pub decision_record_id: Uuid,
    /// User-reported execution outcome.
    pub outcome: ManualExecutionOutcome,
    /// Positive actual amount for executed or partial outcomes.
    pub actual_amount: Option<Decimal>,
    /// Optional user note.
    pub note: Option<String>,
    /// User-reported occurrence time.
    pub occurred_at: OffsetDateTime,
}

impl CreateManualExecutionEvent {
    /// Normalize and validate a manual execution event before persistence.
    pub fn normalize(self) -> Result<Self, ManualExecutionValidationError> {
        if self.id.is_nil() || self.decision_record_id.is_nil() {
            return Err(ManualExecutionValidationError::InvalidIdentifier);
        }
        match (self.outcome, self.actual_amount) {
            (ManualExecutionOutcome::Skipped, None) => {}
            (ManualExecutionOutcome::Skipped, Some(_)) => {
                return Err(ManualExecutionValidationError::UnexpectedActualAmount)
            }
            (ManualExecutionOutcome::Executed | ManualExecutionOutcome::Partial, Some(amount))
                if amount > Decimal::ZERO => {}
            (ManualExecutionOutcome::Executed | ManualExecutionOutcome::Partial, _) => {
                return Err(ManualExecutionValidationError::InvalidActualAmount)
            }
        }
        let note = self.note.map(normalize_manual_execution_note).transpose()?;

        Ok(Self {
            note,
            occurred_at: self.occurred_at.to_offset(time::UtcOffset::UTC),
            ..self
        })
    }
}

/// Validation failures for user-reported manual execution events.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ManualExecutionValidationError {
    /// Event and decision identifiers must be non-nil UUIDs.
    #[error("manual execution identifier is invalid")]
    InvalidIdentifier,
    /// Executed and partial outcomes require a positive actual amount.
    #[error("manual execution actual amount is invalid")]
    InvalidActualAmount,
    /// Skipped outcomes must not claim an actual amount.
    #[error("skipped manual execution must not contain an actual amount")]
    UnexpectedActualAmount,
    /// Notes must be non-blank and within the supported bound.
    #[error("manual execution note is invalid")]
    InvalidNote,
}

/// Storage failures hidden behind the manual execution application layer.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ManualExecutionRepositoryError {
    /// The event did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] ManualExecutionValidationError),
    /// The referenced decision record does not exist.
    #[error("manual execution decision record not found")]
    NotFound,
    /// The event ID already exists and must not be appended again.
    #[error("manual execution event already exists")]
    AlreadyExists,
    /// The storage backend is unavailable.
    #[error("manual execution repository unavailable")]
    Unavailable,
}

/// Application-layer failures for the manual execution journal.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ManualExecutionApplicationError {
    /// The event did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] ManualExecutionValidationError),
    /// The referenced decision record does not exist.
    #[error("manual execution decision record not found")]
    NotFound,
    /// The event ID was already used.
    #[error("manual execution event already exists")]
    AlreadyExists,
    /// The journal backend is unavailable.
    #[error("manual execution journal unavailable")]
    Unavailable,
}

impl From<ManualExecutionRepositoryError> for ManualExecutionApplicationError {
    fn from(error: ManualExecutionRepositoryError) -> Self {
        match error {
            ManualExecutionRepositoryError::Validation(error) => Self::Validation(error),
            ManualExecutionRepositoryError::NotFound => Self::NotFound,
            ManualExecutionRepositoryError::AlreadyExists => Self::AlreadyExists,
            ManualExecutionRepositoryError::Unavailable => Self::Unavailable,
        }
    }
}

/// Outbound append-only repository port for manual execution events.
#[async_trait]
pub trait ManualExecutionRepository: Send + Sync {
    /// Append one event without updating the referenced decision record.
    async fn append(
        &self,
        input: CreateManualExecutionEvent,
    ) -> Result<ManualExecutionEvent, ManualExecutionRepositoryError>;

    /// List all events for a decision in stable journal order.
    async fn list_by_decision(
        &self,
        decision_record_id: Uuid,
    ) -> Result<Vec<ManualExecutionEvent>, ManualExecutionRepositoryError>;
}

/// Application service for append-only user-reported execution events.
#[derive(Clone)]
pub struct ManualExecutionService {
    repository: Arc<dyn ManualExecutionRepository>,
}

impl ManualExecutionService {
    /// Build the service from a repository implementation.
    #[must_use]
    pub fn new(repository: Arc<dyn ManualExecutionRepository>) -> Self {
        Self { repository }
    }

    /// Append one validated user-reported event.
    ///
    /// # Errors
    ///
    /// Returns validation, not-found, duplicate-ID, or backend availability errors.
    pub async fn append(
        &self,
        input: CreateManualExecutionEvent,
    ) -> Result<ManualExecutionEvent, ManualExecutionApplicationError> {
        self.repository
            .append(input.normalize()?)
            .await
            .map_err(Into::into)
    }

    /// List all user-reported events for one immutable decision record.
    ///
    /// # Errors
    ///
    /// Returns [`ManualExecutionApplicationError::Unavailable`] if storage is unavailable.
    pub async fn list_by_decision(
        &self,
        decision_record_id: Uuid,
    ) -> Result<Vec<ManualExecutionEvent>, ManualExecutionApplicationError> {
        if decision_record_id.is_nil() {
            return Err(ManualExecutionValidationError::InvalidIdentifier.into());
        }
        self.repository
            .list_by_decision(decision_record_id)
            .await
            .map_err(Into::into)
    }
}

/// Query options for listing decision records.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecisionRecordListQuery {
    limit: u16,
}

impl DecisionRecordListQuery {
    /// Build a bounded list query.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordValidationError::InvalidListLimit`] when the
    /// requested limit is zero or above the supported maximum.
    pub fn new(limit: u16) -> Result<Self, DecisionRecordValidationError> {
        if limit == 0 || limit > MAX_RECORD_LIST_LIMIT {
            Err(DecisionRecordValidationError::InvalidListLimit)
        } else {
            Ok(Self { limit })
        }
    }

    /// Maximum number of records to return.
    #[must_use]
    pub fn limit(&self) -> u16 {
        self.limit
    }
}

impl Default for DecisionRecordListQuery {
    fn default() -> Self {
        Self {
            limit: DEFAULT_RECORD_LIST_LIMIT,
        }
    }
}

impl CreateDecisionRecord {
    /// Normalize and validate an inbound decision record before persistence.
    pub fn normalize(self) -> Result<Self, DecisionRecordValidationError> {
        let symbol = normalize_symbol(self.symbol)?;
        let currency = normalize_currency(self.currency)?;
        let planned_contribution = self
            .planned_contribution
            .map(normalize_decimal_string)
            .transpose()?;
        validate_snapshot(&self.execution_snapshot, "execution_snapshot")?;
        validate_snapshot(&self.fundamental_snapshot, "fundamental_snapshot")?;
        validate_snapshot(&self.trend_snapshot, "trend_snapshot")?;
        if let Some(snapshot) = &self.sentiment_snapshot {
            validate_snapshot(snapshot, "sentiment_snapshot")?;
        }
        validate_snapshot(&self.decision_snapshot, "decision_snapshot")?;
        if let Some(policy_evidence) = &self.policy_evidence {
            validate_snapshot(
                &policy_evidence.recommendation_snapshot,
                "recommendation_snapshot",
            )?;
        }
        if let Some(snapshot) = &self.broker_order_request {
            validate_snapshot(snapshot, "broker_order_request")?;
        }
        if let Some(snapshot) = &self.broker_order_ack {
            validate_snapshot(snapshot, "broker_order_ack")?;
        }
        let summary = normalize_summary(self.summary)?;

        Ok(Self {
            symbol,
            currency,
            planned_contribution,
            summary,
            ..self
        })
    }
}

impl CompleteDecisionRecord {
    /// Normalize and validate a broker acknowledgement before it completes a record.
    pub fn normalize(self) -> Result<Self, DecisionRecordValidationError> {
        validate_snapshot(&self.broker_order_ack, "broker_order_ack")?;
        let summary = normalize_summary(self.summary)?;

        Ok(Self { summary, ..self })
    }
}

impl AttachBrokerOrderRequest {
    /// Normalize and validate the persisted intent before the broker side effect starts.
    pub fn normalize(self) -> Result<Self, DecisionRecordValidationError> {
        validate_snapshot(&self.broker_order_request, "broker_order_request")?;
        Ok(Self {
            summary: normalize_summary(self.summary)?,
            ..self
        })
    }
}

/// Decision record validation error.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordValidationError {
    /// Symbol is empty, too long, non-ASCII, or contains control characters.
    #[error("decision record symbol is invalid")]
    InvalidSymbol,
    /// Currency is not a three-letter uppercase ASCII code.
    #[error("decision record currency is invalid")]
    InvalidCurrency,
    /// Decimal string is empty, malformed, or non-positive.
    #[error("decision record decimal string is invalid")]
    InvalidDecimalString,
    /// Required JSON snapshot is null.
    #[error("decision record snapshot is invalid: {field}")]
    InvalidSnapshot {
        /// Snapshot field name.
        field: &'static str,
    },
    /// Summary is empty or too long.
    #[error("decision record summary is invalid")]
    InvalidSummary,
    /// Record list limit is zero or too large.
    #[error("decision record list limit is invalid")]
    InvalidListLimit,
}

/// Repository errors hidden behind the application layer.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordRepositoryError {
    /// The decision record did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] DecisionRecordValidationError),
    /// The requested decision record does not exist.
    #[error("decision record not found")]
    NotFound,
    /// The storage backend is unavailable.
    #[error("decision record repository unavailable")]
    Unavailable,
}

/// Application-layer errors for decision records.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordApplicationError {
    /// The decision record did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] DecisionRecordValidationError),
    /// The requested decision record does not exist.
    #[error("decision record not found")]
    NotFound,
    /// The decision record backend is unavailable.
    #[error("decision record backend unavailable")]
    Unavailable,
}

impl From<DecisionRecordRepositoryError> for DecisionRecordApplicationError {
    fn from(error: DecisionRecordRepositoryError) -> Self {
        match error {
            DecisionRecordRepositoryError::Validation(error) => Self::Validation(error),
            DecisionRecordRepositoryError::NotFound => Self::NotFound,
            DecisionRecordRepositoryError::Unavailable => Self::Unavailable,
        }
    }
}

/// Outbound repository port for decision records.
#[async_trait]
pub trait DecisionRecordRepository: Send + Sync {
    /// Persist one decision record snapshot.
    async fn create(
        &self,
        input: CreateDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordRepositoryError>;

    /// Attach the acknowledgement for an order whose intent was already persisted.
    async fn complete_broker_order(
        &self,
        id: Uuid,
        input: CompleteDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordRepositoryError>;

    /// Atomically attach a broker request only when the record has not entered an order flow.
    async fn attach_broker_order_request(
        &self,
        _id: Uuid,
        _input: AttachBrokerOrderRequest,
    ) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
        Err(DecisionRecordRepositoryError::Unavailable)
    }

    /// List newest decision records across all plans for cross-plan review screens.
    async fn list(
        &self,
        _query: DecisionRecordListQuery,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordRepositoryError> {
        Err(DecisionRecordRepositoryError::Unavailable)
    }

    /// List decision records for one investment plan.
    async fn list_by_plan(
        &self,
        plan_id: Uuid,
        query: DecisionRecordListQuery,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordRepositoryError>;

    /// Fetch one decision record by ID.
    async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordRepositoryError>;
}

/// Application service for decision record use cases.
#[derive(Clone)]
pub struct DecisionRecordService {
    repository: Arc<dyn DecisionRecordRepository>,
}

impl DecisionRecordService {
    /// Build the service from a repository implementation.
    #[must_use]
    pub fn new(repository: Arc<dyn DecisionRecordRepository>) -> Self {
        Self { repository }
    }

    /// Persist one decision record snapshot.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn create(
        &self,
        input: CreateDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository
            .create(input.normalize()?)
            .await
            .map_err(Into::into)
    }

    /// Complete a persisted broker-order intention with its acknowledgement.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::NotFound`] when the record does not exist,
    /// or [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn complete_broker_order(
        &self,
        id: Uuid,
        input: CompleteDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository
            .complete_broker_order(id, input.normalize()?)
            .await
            .map_err(Into::into)
    }

    /// Claim an approval record for a single broker submission by persisting its intent first.
    pub async fn attach_broker_order_request(
        &self,
        id: Uuid,
        input: AttachBrokerOrderRequest,
    ) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository
            .attach_broker_order_request(id, input.normalize()?)
            .await
            .map_err(Into::into)
    }

    /// List decision records for one investment plan.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn list_by_plan(
        &self,
        plan_id: Uuid,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordApplicationError> {
        self.list_by_plan_with_query(plan_id, DecisionRecordListQuery::default())
            .await
    }

    /// List newest decision records across all plans with a bounded query.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] when storage is unavailable.
    pub async fn list(
        &self,
        query: DecisionRecordListQuery,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordApplicationError> {
        self.repository.list(query).await.map_err(Into::into)
    }

    /// List decision records for one investment plan with query options.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn list_by_plan_with_query(
        &self,
        plan_id: Uuid,
        query: DecisionRecordListQuery,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordApplicationError> {
        self.repository
            .list_by_plan(plan_id, query)
            .await
            .map_err(Into::into)
    }

    /// Fetch one decision record by ID.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::NotFound`] when the record does not exist,
    /// or [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository.get(id).await.map_err(Into::into)
    }
}

fn normalize_symbol(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty()
        || normalized.len() > MAX_SYMBOL_LEN
        || !normalized.is_ascii()
        || normalized.chars().any(char::is_control)
    {
        return Err(DecisionRecordValidationError::InvalidSymbol);
    }

    Ok(normalized.to_ascii_uppercase())
}

fn normalize_currency(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_ascii_uppercase();
    if normalized.len() == 3
        && normalized
            .chars()
            .all(|character| character.is_ascii_uppercase())
    {
        Ok(normalized)
    } else {
        Err(DecisionRecordValidationError::InvalidCurrency)
    }
}

fn normalize_decimal_string(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim();
    if normalized.is_empty()
        || normalized
            .parse::<Decimal>()
            .map_or(true, |value| value <= Decimal::ZERO)
    {
        Err(DecisionRecordValidationError::InvalidDecimalString)
    } else {
        Ok(normalized.to_owned())
    }
}

fn validate_snapshot(
    value: &Value,
    field: &'static str,
) -> Result<(), DecisionRecordValidationError> {
    if value.is_null() {
        Err(DecisionRecordValidationError::InvalidSnapshot { field })
    } else {
        Ok(())
    }
}

fn normalize_summary(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty() || normalized.len() > MAX_SUMMARY_LEN {
        Err(DecisionRecordValidationError::InvalidSummary)
    } else {
        Ok(normalized)
    }
}

fn normalize_manual_execution_note(
    value: String,
) -> Result<String, ManualExecutionValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty() || normalized.len() > MAX_MANUAL_EXECUTION_NOTE_LEN {
        Err(ManualExecutionValidationError::InvalidNote)
    } else {
        Ok(normalized)
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use serde_json::json;

    use super::*;
    use strategy_policy::{PolicyId, PolicyVersion};

    #[derive(Default)]
    struct FakeRepository {
        records: Mutex<Vec<DecisionRecord>>,
    }

    #[async_trait]
    impl DecisionRecordRepository for FakeRepository {
        async fn create(
            &self,
            input: CreateDecisionRecord,
        ) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
            let mut records = self.records.lock().unwrap();
            let record = record_from(Uuid::from_u128((records.len() + 1) as u128), input);
            records.push(record.clone());
            Ok(record)
        }

        async fn complete_broker_order(
            &self,
            id: Uuid,
            input: CompleteDecisionRecord,
        ) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
            let mut records = self.records.lock().unwrap();
            let record = records
                .iter_mut()
                .find(|record| record.id == id)
                .ok_or(DecisionRecordRepositoryError::NotFound)?;
            record.broker_order_ack = Some(input.broker_order_ack);
            record.summary = input.summary;
            Ok(record.clone())
        }

        async fn list_by_plan(
            &self,
            plan_id: Uuid,
            query: DecisionRecordListQuery,
        ) -> Result<Vec<DecisionRecord>, DecisionRecordRepositoryError> {
            Ok(self
                .records
                .lock()
                .unwrap()
                .iter()
                .filter(|record| record.plan_id == plan_id)
                .take(query.limit().into())
                .cloned()
                .collect())
        }

        async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
            self.records
                .lock()
                .unwrap()
                .iter()
                .find(|record| record.id == id)
                .cloned()
                .ok_or(DecisionRecordRepositoryError::NotFound)
        }
    }

    fn input(plan_id: Uuid) -> CreateDecisionRecord {
        CreateDecisionRecord {
            plan_id,
            symbol: "VOO".to_owned(),
            currency: "USD".to_owned(),
            execution_status: DecisionExecutionStatus::Due,
            planned_contribution: Some("1000.00".to_owned()),
            execution_snapshot: json!({"status": "due"}),
            fundamental_snapshot: json!({"score": 0.2}),
            trend_snapshot: json!({"score": 0.5}),
            sentiment_snapshot: Some(json!({"score": 0.1})),
            decision_snapshot: json!({"action": "standard"}),
            policy_evidence: None,
            broker_order_request: Some(json!({"side": "buy"})),
            broker_order_ack: Some(json!({"status": "accepted"})),
            summary: "standard execution".to_owned(),
        }
    }

    fn record_from(id: Uuid, input: CreateDecisionRecord) -> DecisionRecord {
        DecisionRecord {
            id,
            plan_id: input.plan_id,
            symbol: input.symbol,
            currency: input.currency,
            execution_status: input.execution_status,
            planned_contribution: input.planned_contribution,
            execution_snapshot: input.execution_snapshot,
            fundamental_snapshot: input.fundamental_snapshot,
            trend_snapshot: input.trend_snapshot,
            sentiment_snapshot: input.sentiment_snapshot,
            decision_snapshot: input.decision_snapshot,
            policy_evidence: input.policy_evidence,
            broker_order_request: input.broker_order_request,
            broker_order_ack: input.broker_order_ack,
            summary: input.summary,
            created_at: OffsetDateTime::from_unix_timestamp(1_700_000_000).unwrap(),
        }
    }

    #[tokio::test]
    async fn service_creates_lists_and_gets_records() {
        let repository = Arc::new(FakeRepository::default());
        let service = DecisionRecordService::new(repository);
        let plan_id = Uuid::from_u128(7);
        let created = service.create(input(plan_id)).await.unwrap();

        assert_eq!(created.plan_id, plan_id);
        assert_eq!(created.execution_snapshot, json!({"status": "due"}));
        assert_eq!(
            service.list_by_plan(plan_id).await.unwrap(),
            vec![created.clone()]
        );
        assert_eq!(service.get(created.id).await.unwrap(), created);
    }

    /// Verify new records preserve a validated immutable policy reference and recommendation.
    #[tokio::test]
    async fn service_preserves_structured_policy_evidence() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));
        let mut record = input(Uuid::from_u128(7));
        record.policy_evidence = Some(DecisionPolicyEvidence {
            policy: PolicyRef::new(
                PolicyId::new("fixed_dca").unwrap(),
                PolicyVersion::new(1).unwrap(),
            ),
            recommendation_snapshot: json!({
                "action": "standard",
                "multiplier": 1.0,
                "scheduled_contribution": "1000.00",
                "market_signals_used": false,
            }),
        });

        let created = service.create(record).await.unwrap();
        let evidence = created
            .policy_evidence
            .expect("policy evidence must persist");
        assert_eq!(evidence.policy.to_string(), "fixed_dca@1");
        assert_eq!(
            evidence.recommendation_snapshot["market_signals_used"],
            json!(false)
        );
    }

    /// Verify a persisted order intention can be completed with a broker acknowledgement.
    #[tokio::test]
    async fn service_completes_persisted_broker_order() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));
        let created = service.create(input(Uuid::from_u128(7))).await.unwrap();

        let completed = service
            .complete_broker_order(
                created.id,
                CompleteDecisionRecord {
                    broker_order_ack: json!({"status": "accepted"}),
                    summary: "  paper order accepted  ".to_owned(),
                },
            )
            .await
            .unwrap();

        assert_eq!(
            completed.broker_order_ack,
            Some(json!({"status": "accepted"}))
        );
        assert_eq!(completed.summary, "paper order accepted");
    }

    #[tokio::test]
    async fn service_supports_bounded_list_queries() {
        let repository = Arc::new(FakeRepository::default());
        let service = DecisionRecordService::new(repository);
        let plan_id = Uuid::from_u128(7);
        service.create(input(plan_id)).await.unwrap();
        service.create(input(plan_id)).await.unwrap();

        let listed = service
            .list_by_plan_with_query(plan_id, DecisionRecordListQuery::new(1).unwrap())
            .await
            .unwrap();

        assert_eq!(listed.len(), 1);
    }

    #[tokio::test]
    async fn service_maps_repository_not_found() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));

        assert_eq!(
            service.get(Uuid::from_u128(404)).await,
            Err(DecisionRecordApplicationError::NotFound)
        );
    }

    #[tokio::test]
    async fn service_normalizes_create_input_before_repository() {
        let repository = Arc::new(FakeRepository::default());
        let service = DecisionRecordService::new(repository);
        let mut input = input(Uuid::from_u128(7));
        input.symbol = " voo ".to_owned();
        input.currency = " usd ".to_owned();
        input.planned_contribution = Some(" 1000.00 ".to_owned());
        input.summary = " standard execution ".to_owned();

        let created = service.create(input).await.unwrap();

        assert_eq!(created.symbol, "VOO");
        assert_eq!(created.currency, "USD");
        assert_eq!(created.planned_contribution, Some("1000.00".to_owned()));
        assert_eq!(created.summary, "standard execution");
    }

    #[tokio::test]
    async fn service_rejects_invalid_create_input_before_repository() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));
        let mut invalid_decimal = input(Uuid::from_u128(7));
        invalid_decimal.planned_contribution = Some("NaN".to_owned());

        assert_eq!(
            service.create(invalid_decimal).await,
            Err(DecisionRecordApplicationError::Validation(
                DecisionRecordValidationError::InvalidDecimalString
            ))
        );

        let mut invalid_snapshot = input(Uuid::from_u128(7));
        invalid_snapshot.execution_snapshot = Value::Null;

        assert_eq!(
            service.create(invalid_snapshot).await,
            Err(DecisionRecordApplicationError::Validation(
                DecisionRecordValidationError::InvalidSnapshot {
                    field: "execution_snapshot"
                }
            ))
        );
    }

    #[test]
    fn list_query_rejects_unbounded_limits() {
        assert_eq!(DecisionRecordListQuery::default().limit(), 50);
        assert_eq!(
            DecisionRecordListQuery::new(0),
            Err(DecisionRecordValidationError::InvalidListLimit)
        );
        assert_eq!(
            DecisionRecordListQuery::new(201),
            Err(DecisionRecordValidationError::InvalidListLimit)
        );
    }

    #[test]
    fn normalize_symbol_rejects_invalid_boundaries() {
        assert_eq!(
            normalize_symbol("".to_owned()),
            Err(DecisionRecordValidationError::InvalidSymbol)
        );
        assert_eq!(
            normalize_symbol("V".repeat(33)),
            Err(DecisionRecordValidationError::InvalidSymbol)
        );
        assert_eq!(
            normalize_symbol("åAPL".to_owned()),
            Err(DecisionRecordValidationError::InvalidSymbol)
        );
        assert_eq!(
            normalize_symbol("VO\nO".to_owned()),
            Err(DecisionRecordValidationError::InvalidSymbol)
        );
        assert_eq!(normalize_symbol(" voo ".to_owned()), Ok("VOO".to_owned()));
    }

    #[test]
    fn normalize_currency_rejects_invalid_boundaries() {
        assert_eq!(
            normalize_currency("US".to_owned()),
            Err(DecisionRecordValidationError::InvalidCurrency)
        );
        assert_eq!(
            normalize_currency("US1".to_owned()),
            Err(DecisionRecordValidationError::InvalidCurrency)
        );
        assert_eq!(normalize_currency(" usd ".to_owned()), Ok("USD".to_owned()));
    }

    #[test]
    fn normalize_summary_rejects_invalid_boundaries() {
        assert_eq!(
            normalize_summary("  ".to_owned()),
            Err(DecisionRecordValidationError::InvalidSummary)
        );
        assert_eq!(
            normalize_summary("x".repeat(MAX_SUMMARY_LEN + 1)),
            Err(DecisionRecordValidationError::InvalidSummary)
        );
        assert_eq!(
            normalize_summary(" useful summary ".to_owned()),
            Ok("useful summary".to_owned())
        );
    }

    #[tokio::test]
    async fn service_rejects_all_null_snapshot_boundaries() {
        type MutateInput = fn(&mut CreateDecisionRecord);
        let cases: [(&str, MutateInput); 6] = [
            (
                "fundamental_snapshot",
                |input: &mut CreateDecisionRecord| {
                    input.fundamental_snapshot = Value::Null;
                },
            ),
            ("trend_snapshot", |input: &mut CreateDecisionRecord| {
                input.trend_snapshot = Value::Null;
            }),
            ("decision_snapshot", |input: &mut CreateDecisionRecord| {
                input.decision_snapshot = Value::Null;
            }),
            ("sentiment_snapshot", |input: &mut CreateDecisionRecord| {
                input.sentiment_snapshot = Some(Value::Null);
            }),
            (
                "broker_order_request",
                |input: &mut CreateDecisionRecord| {
                    input.broker_order_request = Some(Value::Null);
                },
            ),
            ("broker_order_ack", |input: &mut CreateDecisionRecord| {
                input.broker_order_ack = Some(Value::Null);
            }),
        ];

        for (field, mutate) in cases {
            let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));
            let mut input = input(Uuid::from_u128(7));
            mutate(&mut input);

            assert_eq!(
                service.create(input).await,
                Err(DecisionRecordApplicationError::Validation(
                    DecisionRecordValidationError::InvalidSnapshot { field }
                ))
            );
        }
    }

    fn manual_input(outcome: ManualExecutionOutcome) -> CreateManualExecutionEvent {
        CreateManualExecutionEvent {
            id: Uuid::from_u128(41),
            decision_record_id: Uuid::from_u128(42),
            outcome,
            actual_amount: Some(Decimal::new(7500, 2)),
            note: Some(" completed in my broker ".to_owned()),
            occurred_at: OffsetDateTime::from_unix_timestamp(1_700_000_000).unwrap(),
        }
    }

    #[test]
    fn manual_execution_normalizes_note_and_enforces_outcome_amount_contract() {
        let normalized = manual_input(ManualExecutionOutcome::Partial)
            .normalize()
            .unwrap();
        assert_eq!(normalized.actual_amount, Some(Decimal::new(7500, 2)));
        assert_eq!(normalized.note.as_deref(), Some("completed in my broker"));

        let mut skipped_with_amount = manual_input(ManualExecutionOutcome::Skipped);
        assert_eq!(
            skipped_with_amount.clone().normalize(),
            Err(ManualExecutionValidationError::UnexpectedActualAmount)
        );
        skipped_with_amount.actual_amount = None;
        assert!(skipped_with_amount.normalize().is_ok());

        let mut executed_without_amount = manual_input(ManualExecutionOutcome::Executed);
        executed_without_amount.actual_amount = None;
        assert_eq!(
            executed_without_amount.normalize(),
            Err(ManualExecutionValidationError::InvalidActualAmount)
        );
    }

    #[test]
    fn manual_execution_rejects_invalid_identifiers_amounts_and_notes() {
        let mut invalid_id = manual_input(ManualExecutionOutcome::Executed);
        invalid_id.id = Uuid::nil();
        assert_eq!(
            invalid_id.normalize(),
            Err(ManualExecutionValidationError::InvalidIdentifier)
        );

        let mut invalid_amount = manual_input(ManualExecutionOutcome::Partial);
        invalid_amount.actual_amount = Some(Decimal::ZERO);
        assert_eq!(
            invalid_amount.normalize(),
            Err(ManualExecutionValidationError::InvalidActualAmount)
        );

        let mut invalid_note = manual_input(ManualExecutionOutcome::Executed);
        invalid_note.note = Some(" ".to_owned());
        assert_eq!(
            invalid_note.normalize(),
            Err(ManualExecutionValidationError::InvalidNote)
        );
    }
}
